language: csharp
os: linux
dist: xenial
sudo: required
mono: none
dotnet: 2.1.4
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./deploycontainer.sh
script:
  - dotnet build -c Release sfintegration
deploy:
  - provider: script
    script: ./deploycontainer.sh $TRAVIS_TAG $TRAVIS_BRANCH $DOCKER_USERNAME $DOCKER_PASSWORD
    skip_cleanup: true
    on:
      tags: true
