language: csharp
os: linux
sudo: required
mono: none
dotnet: 2.1.4
branches:
  only:
  - master
  - sridmad
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./deploycontainer.sh
script:
  - ./deploycontainer.sh $TRAVIS_TAG $TRAVIS_BRANCH $DOCKER_USERNAME $DOCKER_PASSWORD
