language: csharp
services:
  - docker
os: linux
sudo: required
mono: none
dotnet: 2.1.402
branches:
  only:
  - master
  - sridmad
install:
  - export DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod a+x ./deploycontainer.sh
script:
  - ./deploycontainer.sh $TRAVIS_BRANCH $TRAVIS_COMMIT $DOCKER_USERNAME $DOCKER_PASSWORD $TRAVIS_TAG
